version: '3.0'

services:
  grafana:
    container_name: 'isaozler-shiftselector-panel'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-11.0.0}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/isaozler-shiftselector-panel
      - ./provisioning:/etc/grafana/provisioning
